#!/bin/bash
#####################
## variable define ##
#####################
server_container_type=jetty # tomcat|jetty
server_path=/data2/zzw/jetty/jetty-distribution-9.4.19.v20190610/
echo_msg='调用webgis_server_restart脚本'

#####################
## function define ##
#####################

# 重启服务.
function server_restart() {
	echo '===== 关闭服务器 ====='
	echo "执行命令: ps aux | grep -v grep | grep $server_container_type | grep $server_path | awk '{print \$2}' | xargs kill -9"
	ps aux | grep -v grep | grep $server_container_type | grep $server_path | awk '{print $2}' | xargs kill -9
	echo '===== 重启服务器 ====='
	if [[ $webgis_server_container_type == "tomcat" ]]; then
		bash $webgis_server_path/bin/startup.sh
		echo "执行命令: bash $server_path/bin/startup.sh"
	elif [[ $webgis_server_container_type == "jetty" ]]; then
		echo "执行命令: bash $webgis_server_path/bin/jetty.sh restart"
		bash $server_path/bin/jetty.sh restart
	else
		echo '服务器类型类型未知! 请检查 webgis_server_container_type 配置项!'
	fi
}


# main
echo '============================='
echo $echo_msg
echo '============================='
server_restart
